import Head from "next/head";
import React from "react";
import Footer from "./Footer/Footer";
import Navbar from "./Navbar/Navbar";
import Product from "./Product/Product";
import Slider from "./Slider/Slider";
const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
          <Navbar></Navbar>
        </header>
        <div className="mt-2">
          <main>
            {children}
            <Slider />
            <div>
                <Product></Product>
            </div>
          </main>
        </div>
        <footer>
          <Footer/>
        </footer>
      </div>
    </>
  );
};

export default Layout;
export async function getStaticProps(context) {
    const res = await fetch("https://jsonplaceholder.typicode.com/users");
    const data = await res.json();
    return {
      props: {users:data}, // will be passed to the page component as props
    };
  }
  