import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../pages/Navbar/Navbar'
import Slider from '../pages/Slider/Slider'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar></Navbar>
        <Slider></Slider>
      </main>

      
    </div>
  )
}
